// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"dailyreport/controller"
	"dailyreport/repository"
	"dailyreport/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitDailyReport(db *gorm.DB) controller.DailyReportController {
	dailyReportRepository := repository.NewDailyReportRepository(db)
	dailyReportService := service.NewDailyReportService(dailyReportRepository)
	dailyReportController := controller.NewDailyReportController(dailyReportService)
	return dailyReportController
}

// injector.go:

var dailyreportSet = wire.NewSet(repository.NewDailyReportRepository, service.NewDailyReportService, controller.NewDailyReportController)
